import 'menu_item.dart';

class MenuData {
  static final List<MenuItem> coffeeItems = [
    MenuItem(
      id: 'espresso',
      name: 'Espresso',
      description: 'Short Black - Rich and intense',
      price: 3.50,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.hot,
      emoji: '☕',
    ),
    MenuItem(
      id: 'americano',
      name: 'Americano',
      description: 'Long Black - Bold and smooth',
      price: 4.00,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.hot,
      emoji: '☕',
    ),
    MenuItem(
      id: 'flat_white',
      name: 'Flat White',
      description: 'Velvety microfoam perfection',
      price: 4.50,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.hot,
      emoji: '🥛',
    ),
    MenuItem(
      id: 'latte',
      name: 'Café au Lait',
      description: 'Latte - Creamy and mild',
      price: 4.50,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.hot,
      emoji: '🥛',
    ),
    MenuItem(
      id: 'cappuccino',
      name: 'Cappuccino',
      description: 'Classic foam-topped delight',
      price: 4.50,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.hot,
      emoji: '☕',
    ),
    MenuItem(
      id: 'black_coffee',
      name: 'Black Coffee',
      description: 'Fresh brewed - Pure and simple',
      price: 3.00,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.hot,
      emoji: '☕',
    ),
    MenuItem(
      id: 'iced_americano',
      name: 'Iced Americano',
      description: 'Chilled Long Black',
      price: 4.50,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.iced,
      emoji: '🧊',
    ),
    MenuItem(
      id: 'iced_latte',
      name: 'Iced Latte',
      description: 'Cold and creamy',
      price: 5.00,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.iced,
      emoji: '🧊',
    ),
    MenuItem(
      id: 'iced_coffee',
      name: 'Iced Coffee',
      description: 'Refreshing cold brew',
      price: 4.50,
      category: ItemCategory.coffee,
      temperature: CoffeeTemperature.iced,
      emoji: '🧊',
    ),
  ];

  static final List<MenuItem> patisserieItems = [
    MenuItem(
      id: 'almond_croissant',
      name: 'Almond Croissant',
      description: 'Flaky pastry with almond cream',
      price: 4.50,
      category: ItemCategory.patisserie,
      emoji: '🥐',
    ),
    MenuItem(
      id: 'granola_bowl',
      name: 'Granola Bowl',
      description: 'House-made granola with yogurt',
      price: 6.00,
      category: ItemCategory.patisserie,
      emoji: '🥣',
    ),
    MenuItem(
      id: 'banana_bread',
      name: 'Banana Bread',
      description: 'Moist and wholesome',
      price: 4.00,
      category: ItemCategory.patisserie,
      emoji: '🍌',
    ),
    MenuItem(
      id: 'oat_muffin',
      name: 'Oat Muffin',
      description: 'Healthy blueberry oat muffin',
      price: 3.50,
      category: ItemCategory.patisserie,
      emoji: '🧁',
    ),
    MenuItem(
      id: 'protein_ball',
      name: 'Protein Energy Balls',
      description: 'Date and nut energy bites',
      price: 5.00,
      category: ItemCategory.patisserie,
      emoji: '🥜',
    ),
    MenuItem(
      id: 'avocado_toast',
      name: 'Avocado Toast',
      description: 'Sourdough with fresh avocado',
      price: 7.00,
      category: ItemCategory.patisserie,
      emoji: '🥑',
    ),
  ];

  static List<MenuItem> get allItems => [...coffeeItems, ...patisserieItems];
}
